language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tordanf/dockertest -f Dockerfile.dev .

script:
  - docker run -e CI=true tordanf/dockertest npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerTest"
  env: "Dockertest-env"
  bucket_name: "elasticbeanstalk-us-east-2-248183079538"
  bucket_path: "DockerTest"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
